name: Run Tests
env:
  CARGO_TERM_COLOR: always
on:
  workflow_run:
    workflows: ["Run Linting, Formatting and Code Coverage Check"]
    types:
      - completed
    status: success
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [fmt, clippy, coverage]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust
      - name: Run tests
      - run: cargo test --all-features

