name: Run Tests
env:
  CARGO_TERM_COLOR: always
on:
  workflow_run:
    workflows: ["Run Linting, Formatting and Code Coverage Check"]
    types:
      - completed
    status: success
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo test --all-features